/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pork5VEhsjX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function Component() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-blue-900 text-white py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link className="flex items-center gap-2" href="#">
            <LogInIcon className="w-8 h-8" />
            <span className="text-lg font-bold">Talent Management</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link className="hover:text-blue-200" href="#">
              Dashboard
            </Link>
            <Link className="hover:text-blue-200" href="#">
              Candidates
            </Link>
            <Link className="hover:text-blue-200" href="#">
              Activities
            </Link>
            <Link className="hover:text-blue-200" href="#">
              Settings
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          <Button className="rounded-full" size="icon" variant="ghost">
            <SignalIcon className="w-6 h-6" />
            <span className="sr-only">Notifications</span>
          </Button>
          <Avatar className="w-10 h-10 border">
            <AvatarImage alt="@username" src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <div className="flex-1 grid grid-cols-[240px_1fr] gap-6 p-6">
        <div className="bg-white rounded-lg shadow-md p-4">
          <Collapsible className="grid gap-4">
            <CollapsibleTrigger
              className="flex items-center justify-between text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Dashboard
              <ChevronRightIcon className="w-5 h-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <nav className="grid gap-2">
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Overview
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Analytics
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Reports
                </Link>
              </nav>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid gap-4">
            <CollapsibleTrigger
              className="flex items-center justify-between text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Candidates
              <ChevronRightIcon className="w-5 h-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <nav className="grid gap-2">
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  All Candidates
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Add Candidate
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Pipeline
                </Link>
              </nav>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid gap-4">
            <CollapsibleTrigger
              className="flex items-center justify-between text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Activities
              <ChevronRightIcon className="w-5 h-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <nav className="grid gap-2">
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  All Activities
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Add Activity
                </Link>
              </nav>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid gap-4">
            <CollapsibleTrigger
              className="flex items-center justify-between text-lg font-medium [&[data-state=open]>svg]:rotate-90">
              Settings
              <ChevronRightIcon className="w-5 h-5 transition-transform" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <nav className="grid gap-2">
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  General
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Users
                </Link>
                <Link
                  className="hover:bg-gray-100 light:hover:bg-gray-800 px-3 py-2 rounded-md"
                  href="#">
                  Integrations
                </Link>
              </nav>
            </CollapsibleContent>
          </Collapsible>
        </div>
        <div className="grid gap-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>New Candidates</CardTitle>
                <UserPlusIcon className="w-6 h-6 text-blue-500" />
              </CardHeader>
              <CardContent className="text-3xl font-bold">124</CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Open Positions</CardTitle>
                <BriefcaseIcon className="w-6 h-6 text-blue-500" />
              </CardHeader>
              <CardContent className="text-3xl font-bold">32</CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Interviews Scheduled</CardTitle>
                <CalendarIcon className="w-6 h-6 text-blue-500" />
              </CardHeader>
              <CardContent className="text-3xl font-bold">18</CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Offers Made</CardTitle>
                <CheckIcon className="w-6 h-6 text-blue-500" />
              </CardHeader>
              <CardContent className="text-3xl font-bold">9</CardContent>
            </Card>
          </div>
          <Card>
            <CardHeader>
              <CardTitle>Activity Feed</CardTitle>
              <div className="flex items-center gap-2">
                <Button className="rounded-full" size="icon" variant="ghost">
                  <FilterIcon className="w-5 h-5" />
                  <span className="sr-only">Filter</span>
                </Button>
                <Button className="rounded-full" size="icon" variant="ghost">
                  <RefreshCwIcon className="w-5 h-5" />
                  <span className="sr-only">Refresh</span>
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-start gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1">
                    <div className="flex items-center gap-2">
                      <div className="font-medium">John Doe</div>
                      <div className="text-gray-500 text-sm">2 hours ago</div>
                    </div>
                    <div>
                      <p>Reviewed and approved the candidate profile for Jane Smith.</p>
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                    <AvatarFallback>SA</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1">
                    <div className="flex items-center gap-2">
                      <div className="font-medium">Sarah Anderson</div>
                      <div className="text-gray-500 text-sm">4 hours ago</div>
                    </div>
                    <div>
                      <p>Scheduled an interview with candidate John Doe for next week.</p>
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                    <AvatarFallback>MJ</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1">
                    <div className="flex items-center gap-2">
                      <div className="font-medium">Michael Johnson</div>
                      <div className="text-gray-500 text-sm">1 day ago</div>
                    </div>
                    <div>
                      <p>Moved candidate Jane Smith to the interview stage.</p>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Candidate Management</CardTitle>
              <div className="flex items-center gap-2">
                <Input className="max-w-xs" placeholder="Search candidates..." type="search" />
                <Button>Add Candidate</Button>
              </div>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Phone</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8 border">
                          <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>John Doe</div>
                      </div>
                    </TableCell>
                    <TableCell>john.doe@example.com</TableCell>
                    <TableCell>+1 (555) 123-4567</TableCell>
                    <TableCell>
                      <Badge variant="success">Hired</Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <EyeIcon className="w-5 h-5" />
                          <span className="sr-only">View</span>
                        </Button>
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <FilePenIcon className="w-5 h-5" />
                          <span className="sr-only">Edit</span>
                        </Button>
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <TrashIcon className="w-5 h-5" />
                          <span className="sr-only">Delete</span>
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8 border">
                          <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                          <AvatarFallback>JS</AvatarFallback>
                        </Avatar>
                        <div>Jane Smith</div>
                      </div>
                    </TableCell>
                    <TableCell>jane.smith@example.com</TableCell>
                    <TableCell>+1 (555) 987-6543</TableCell>
                    <TableCell>
                      <Badge variant="warning">Interview</Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <EyeIcon className="w-5 h-5" />
                          <span className="sr-only">View</span>
                        </Button>
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <FilePenIcon className="w-5 h-5" />
                          <span className="sr-only">Edit</span>
                        </Button>
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <TrashIcon className="w-5 h-5" />
                          <span className="sr-only">Delete</span>
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8 border">
                          <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                          <AvatarFallback>MJ</AvatarFallback>
                        </Avatar>
                        <div>Michael Johnson</div>
                      </div>
                    </TableCell>
                    <TableCell>michael.johnson@example.com</TableCell>
                    <TableCell>+1 (555) 456-7890</TableCell>
                    <TableCell>
                      <Badge variant="danger">Rejected</Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Button className="rounded-full" size="icon" variant="ghost">
                          <EyeIcon className="w-5 h-5" />
                          <span className="sr-only">View</span>
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>)
  );
}

function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>)
  );
}


function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function EyeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function FilePenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>)
  );
}


function FilterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>)
  );
}


function LogInIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>)
  );
}


function RefreshCwIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>)
  );
}


function SignalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}


function UserPlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <line x1="19" x2="19" y1="8" y2="14" />
      <line x1="22" x2="16" y1="11" y2="11" />
    </svg>)
  );
}
